analyze_map.go, analyze_map_test.go, analyze_test.go, parse.go
The current validation of a map block would check that all parameters had exactly 1 argument. This would cause parse errors on valid configs with other "map-like" directives and "special parameters". For example, the `volatile` parameter can be used without any additional arguments inside the [`map` directive](http://nginx.org/en/docs/http/ngx_http_map_module.html#map). 
Different directives also have different constraints on how many arguments a parameter can have, for example, parameter's in [`match`](http://nginx.org/en/docs/http/ngx_http_upstream_hc_module.html#match) can have 1 or more arguments.
```
http {
match check {
require $variable ...;
}
}
```
This improves the previous rudimentary validation to use the bit masks, so each directive can be customized so their bodies can have …
=> Fix analyze map body validation

analyze_map.go, analyze_map_test.go, parse_test.go, testdata/configs/types/nginx.conf
`types` is a "map-like" directive meaning its body does not contain additional NGINX directives. Previously, if the body of the `types` directive was not empty, crossplane would fail to parse it because it did not recognize its contents as NGINX directives. This fixes this behavior by adding `types` to the set of map-like directives and validating only that each entry has the correct number of arguments, 1 or more.
For an example of the `types` directive, see http://nginx.org/en/docs/http/ngx_http_core_module.html#types.
=> fix: validate body of types directive

analyze.go
A few njs directives are missing from the allow list that were added in newer releases. This set includes:
* `js_fetch_buffer_size`
* `js_fetch_max_response_buffer_size`
* `js_fetch_timeout`
* `js_fetch_verify`
* `js_preload_object`
For more information on the contexts these directives may be specified in and the number of arguments they may have, see https://nginx.org/en/docs/http/ngx_http_js_module.html and https://nginx.org/en/docs/stream/ngx_stream_js_module.html
I skipped adding to any unit tests since we aren't testing every single NGINX directive and existing coverage that `analyze` works should be enough. 
=> add missing njs directives

analyze.go
Fixes spelling of `fastcgi_next_upstream_timeout` and `fastcgi_next_upstream_tries`. See https://nginx.org/en/docs/http/ngx_http_fastcgi_module.html for info on these directives.
=> fix fastcgi_next_upstream_ directives spelling

.golangci.yml
I don't see a good reason to keep this. Omitting struct fields to default to their empty value is how Go works. I don't see much reason to set slice fields to `nil`, ints to `0`, etc.
The linter itself is archived and has a note in the read me that:
> This linter is meant to be used only for special cases. It is not
> recommended to use it for all files in a project.
Our cases aren't special.
=> Removes unnecessary exhaustivestruct linter

.golangci.yml, analyze.go, analyze_test.go, build.go, build_test.go, lex.go, lex_test.go, parse.go, parse_bench_test.go, parse_test.go, types_test.go
- Modify `.golangci.yml` to suppress `cyclops`, `depguard` and `varnamelen` linters
- Suppress linters such as `funlen` and `gocognit` to avoid huge logic change
- use `t.Log()` for logging errors in testing to fix the `forbidigo` linter
- Update deprecated functions from `io/ioutil`
- Use `utf8.DecodeRuneInString` instead of `utf8.DecodeRuneIn` for the `mirror` linter
- Drop `=0` for `var` declaration to fix the `revive` linter
- Remove leading spaces for `nolintlint`
- Remove unused linter 
=> fix: add changes for linter

analyze.go, analyze_map.go, analyze_map_test.go
https://docs.nginx.com/nginx/admin-guide/security-controls/controlling-access-by-geoip/ we officially recommend using GeoIP2 for
allow/restricting based on location and should
handle it in crossplane as well.
=> Allow parsing of geoip2 module

analyze.go
The new http2 directive obsoletes the http2
parameter of the listen directive which is
now deprecated.
https://docs.nginx.com/nginx/releases/#nginxplusrelease-30-r30
http://nginx.org/en/docs/http/ngx_http_v2_module.html#http2
=> Add support for http2 directive

analyze.go
Small addition of `internal_redirect` to list of allowed directives to be parsed.
=> NLB-3337: allow 'internal_redirect' in parser

analyze.go, analyze_test.go
add the http3 module to the parser.
https://nginx.org/en/docs/http/ngx_http_v3_module.html
=> NLB-3682: Allow parsing for  http3 module

analyze.go, analyze_map.go, analyze_map_test.go
https://nginx.org/en/docs/ngx_otel_module.html
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
=> Allow otel module directives

analyze.go
https://nginx.org/en/docs/mail/ngx_mail_auth_http_module.html
These directives are not valid nginx directives and the change fixes these directives
https://nginx.org/en/docs/mail/ngx_mail_auth_http_module.html
=> Fix directive names for auth_http_*

analyze.go
The changes add missing directives from `ngx_mail_core_module` and `ngx_mail_proxy_module` 
=> Add missing mail module directives

analyze.go
Resolves #72.
The mask `ngxAnyConf` is defined as "any context except `server > if`, `location > if` and `location > limit_except`".
Given that this mask is only used for defining the valid contexts for the `include` directive, and given that the contexts listed above are valid for `include`, it makes sense to modify the `ngxAnyConf` definition to include such contexts.
=> fix: allow 'include' directive in 'if' and 'limit_except' blocks

analyze.go, analyze_test.go
Add missing `zone_sync_ssl_conf_command` directive
https://nginx.org/en/docs/stream/ngx_stream_zone_sync_module.html
=> fix: add missing zone_sync_ssl_conf_command directive

parse_bench_test.go
`TestMain` is used for all tests, not just benchmarks as it looks like the file might expect. The error code was being ignored which results in an `ok` status on each test run even when there are failures.
This commit fixes `TestMain` to return the error code returned from `Run()`. I did not look at anything else going on in the file.
=> Fixes error code on test run

analyze.go, analyze_test.go, parse.go, parse_test.go, testdata/configs/nap-waf-v4/nginx.conf, testdata/configs/nap-waf-v5/nginx.conf
Added an API for allowing the caller of `Parse` to specify bitmasks for directives outsides the "core" set of NGINX directives. This would allow the caller to parse an NGINX configuration that contained directives from a dynamic module even if it is a unknown custom one as long as the configuration still matches the expected grammar.
As part of this I moved the NAP WAF v4 directives out of the main `directives` map before adding directives for WAF v5. The two versions of this module have a different set of directives that I did not want to layer on top of each other. I want to specifically call out that this means the v4 directives are **not** included in the main directives dictionary which means a configuration using v4 NAP directives that was parsed without error before updating …
=> Implements NGINX App Protect v5 modules through custom parse options

analyze.go, analyze_test.go
Enable crossplane to recognize `js_shared_dict_zone` directive with `ngx_http_js_module` and `ngx_stream_js_module`
=> Allow directive js_shared_dict_zone

analyze.go, analyze_test.go
add support for headers-more module  https://github.com/openresty/headers-more-nginx-module?tab=readme-ov-file#directives
reference to https://github.com/openresty/headers-more-nginx-module/blob/06dc0be56e5ec9f7fd814e881b066b5540a85bec/src/ngx_http_headers_more_filter_module.c#L41
=> NLB-4932: add support for headers-more

analyze_test.go, build.go, build_test.go, lex.go, lex_test.go, lua.go, parse_test.go
Moves the "register" responsibility to the options types, not 100% on the API, but it's an idea. The interfaces are now single-method which is pretty much as small as it gets. You could implement these interfaces with a single function that calls itself.
A benefit to this is most obvious with the external Lexer I think as now it is not responsible for storing a value for later use that carries state and is not concurrent-safe.
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
Before creating a PR, run through this …
=> Refactor idea to simplify interfaces

analyze.go, analyze_test.go, parse.go
Add a `DirectiveSources` field in `ParseOptions`. This field aims for users to indicate the OSS/N+ version, and dynamic modules they want to include for validation. If it is provided, it will be the only source of directives included in validation, and `ParseOptions.MatchFuncs` will be ignored
=> Add `DirectiveSources` field to `ParseOptions`

buffer.go, parse.go
The parse function was leaking memory. On analysis of the code it looked like the fileOpen function was keeping the memory active, after the file was being used. 
* Changed the io.Reader to io.ReadCloser in Open signature
* Changed the io.Reader to io.ReadCloser in osOpen signature
* Added defer to close the file after function exit in Parse
A snapshot of the memory in the NGINX Agent before these changes:
and after:
=> fix: Memory leak caused by openFile and osOpen functions

analyze_nplus_latest_directives.go, analyze_test.go, parse_test.go, testdata/configs/limit-req-zone/nginx.conf
In #100 we provided support files for `ParseOptions.DirectiveSources`. For some reason `analyze_nplus_latest_directives.go` was override to a legacy version with mismatch from `NGX_CONF_TAKE4` to `ngxConfTake2`. This PR is to fix those directives(`keyval` and `limit_req_zone`). Thanks to @oliveromahony found this problem.
=> Fix Nplus directives definition

parse.go
Add one nil pointer check to avoid panic.
=> Add one nil pointer check to avoid panic

tools.go
When you import this package, the [gopls](https://pkg.go.dev/golang.org/x/tools/gopls) language server reports the following error:
```
found packages crossplane (analyze.go) and tools (tools.go) in $GOPATH/pkg/mod/github.com/nginxinc/nginx-go-crossplane@v0.4.63go list
```
This doesn't actually affect usage, it's just kind of annoying since there's no way to disable this error:
This PR:
- Changes the package from `tools` to `crossplane`
- Changes the imports themselves to non-main packages
This will eliminate the errors since they're now the same package and refer to non-main packages. This should be a no-op, it just fixes the IDE errors. 
Calling `go mod tidy` will still download these tools (you'll notice no changes to `go.mod` or `go.sum`) and with the build (`go:build tools`) …
=> package tools => package crossplane

analyze_nplus_R35_directives.gen.go, analyze_nplus_latest_directives.gen.go, analyze_test.go, scripts/generate/configs/nplus_R35_config.json
Manually create the config JSON files by comparing the directives, then use the generator to create the directives.gen.go files.
To secure the private link in the public repositories, we will use environment variables.
New directives introduced in R35:
For [Native OIDC Module](https://nginx.org/en/docs/http/ngx_http_oidc_module.html)
- logout_uri
- post_logout_uri
- logout_token_hint
- userinfo
For [Auth Require Module](https://nginx.org/en/docs/http/ngx_http_auth_require_module.html)
- [auth_require ](https://nginx.org/en/docs/http/ngx_http_auth_require_module.html#auth_require)
For [For  ngx_http_core_module](https://nginx.org/en/docs/http/ngx_http_core_module.html)
- [early_hints](https://nginx.org/en/docs/http/ngx_http_core_module.html#early_hints)
Filtered the `ssl_verify_digests` …
=> NLB-6931: Enable R35 directives
